## Machine Learning


### Laura Licerio

In [3]:
#Genera una matriz cuadrada de 4x4
import numpy as np
matriz=np.array([[2,4,6,8],[1,3,5,7],[10,12,14,16],[9,11,13,15]])
print (matriz)

[[ 2  4  6  8]
 [ 1  3  5  7]
 [10 12 14 16]
 [ 9 11 13 15]]


In [5]:
#Calcula su inversa y su traspuesta.
matriz_inversa = np.linalg.inv(matriz)
print (matriz_inversa)
matriz_traspuesta = matriz.T
print (matriz_traspuesta)

[[ 7.29456278e+14 -1.26861961e+15 -5.04276296e+15  5.58192630e+15]
 [ 8.88033729e+15 -7.61171768e+15  1.26861961e+15 -2.53723923e+15]
 [-1.99490434e+16  1.90292942e+16  1.25910497e+16 -1.16713004e+16]
 [ 1.03392498e+16 -1.01489569e+16 -8.81690631e+15  8.62661337e+15]]
[[ 2  1 10  9]
 [ 4  3 12 11]
 [ 6  5 14 13]
 [ 8  7 16 15]]


In [6]:
#Multiplica la matriz por un escalar
escalar=7
multiplicacion_escalar = matriz * escalar
print (multiplicacion_escalar)

[[ 14  28  42  56]
 [  7  21  35  49]
 [ 70  84  98 112]
 [ 63  77  91 105]]


In [9]:
# Realiza el producto interno con una nueva matriz de dimensiones 4x2.
matriz_2 = np.array([[5,1],[8,3],[6,2],[4,7]])
producto = np.dot(matriz, matriz_2)
print (producto)

[[110  82]
 [ 87  69]
 [294 186]
 [271 173]]
